#theme: jekyll-theme-minimal

### Site Settings ###
title               : Duygu Sezen Islakoglu
#description         : duyguislakoglu@gmail.com 

repository          : https://github.com/duyguislakoglu    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Duygu Sezen Islakoğlu
  image             : logo.png
  email             : duyguislakoglu@gmail.com
  github            : duyguislakoglu
  linkedin          : duygu-sezen-islakoglu
  medium            : duyguislakoglu


### Pagination ###
paginate: 6
#paginate_path: "/articles/page-:num/"


### Posts Permalink ###
#permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

plugins:
  - jemoji

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
